import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from vanna.chromadb import ChromaDB_VectorStore
from vanna.ollama import Ollama

# =========================================================
# 1. LOAD CẤU HÌNH
# =========================================================
load_dotenv(dotenv_path="../.env")

# =========================================================
# 2. CUSTOM VANNA CLASS - CHẠY 100% OFFLINE (OLLAMA)
# =========================================================
class MyVanna(ChromaDB_VectorStore, Ollama):
    def __init__(self):
        # Trí nhớ của AI lưu tại thư mục vanna_db trong máy
        ChromaDB_VectorStore.__init__(self, config={"path": "./vanna_db"})

        Ollama.__init__(self, config={
            "model": " qwen2.5-coder:3b", 
            "ollama_host": "http://localhost:11434"
        })

# Khởi tạo instance
vn = MyVanna()

# =========================================================
# 3. KẾT NỐI POSTGRESQL (Cổng 5432)
# =========================================================
vn.connect_to_postgres(
    host=os.getenv("DB_HOST"),
    dbname=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASS"),
    port=os.getenv("DB_PORT")
)

# =========================================================
# 4. HÀM LUYỆN AI (SCHEMA 11 BẢNG)
# =========================================================
def train_warehouse():
    print("--- 🧠 Đang nạp cấu trúc CSDL KLTN vào trí nhớ Offline... ---")
    
    # Nạp toàn bộ DDL (Data Definition Language)
    vn.train(ddl="""
        CREATE TABLE public.categories (category_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, category_name VARCHAR(100) NOT NULL, description TEXT, created_by INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN DEFAULT false, logo VARCHAR(255), status BOOLEAN DEFAULT true);
        
        CREATE TABLE public.products (product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, product_name VARCHAR(150) NOT NULL, category_id INTEGER NOT NULL, is_deleted BOOLEAN DEFAULT false, created_by INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, product_image VARCHAR(255), status BOOLEAN DEFAULT true, image_embedding vector(512));
        
        CREATE TABLE public.product_variants (variant_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, product_id INTEGER NOT NULL, size VARCHAR(10) NOT NULL, color VARCHAR(50) NOT NULL, is_deleted BOOLEAN DEFAULT false, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, stock INTEGER DEFAULT 0, status BOOLEAN DEFAULT true, sku VARCHAR(50));
        
        CREATE TABLE public.users (user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, username VARCHAR(50) NOT NULL, password_hash VARCHAR(255) NOT NULL, full_name VARCHAR(100), role VARCHAR(20) NOT NULL, status BOOLEAN DEFAULT true, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_deleted BOOLEAN DEFAULT false, phone_number VARCHAR(20), address TEXT);
        
        CREATE TABLE public.transactions (transaction_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, transaction_type VARCHAR(20) NOT NULL, variant_id INTEGER NOT NULL, quantity INTEGER NOT NULL, user_id INTEGER, reference_id VARCHAR(50), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.ai_forecasts (forecast_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, variant_id INTEGER NOT NULL, forecast_month DATE NOT NULL, predicted_demand INTEGER, suggested_import INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.chat_history (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, user_id INTEGER NOT NULL, message TEXT NOT NULL, response TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.inventory (inventory_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, variant_id INTEGER NOT NULL, shelf_id INTEGER NOT NULL, quantity INTEGER NOT NULL, last_updated_by INTEGER, last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.pending_imports (approval_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, staff_id INTEGER NOT NULL, image_url TEXT, suggested_qty INTEGER, ai_recognized JSONB, status VARCHAR(20) DEFAULT 'PENDING', manager_id INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.shelves (shelf_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, location_code VARCHAR(50) NOT NULL, description TEXT, created_by INTEGER, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
        
        CREATE TABLE public.system_logs (log_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, user_id INTEGER, action_type VARCHAR(50) NOT NULL, table_affected VARCHAR(50), details JSONB, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    """)
    
    # Nạp quy tắc nghiệp vụ (Documentation)
    vn.train(documentation="""
        LUẬT HỆ THỐNG SMART WAREHOUSE:
        1. LIÊN KẾT: categories(category_id) <- products(category_id) | products(product_id) <- product_variants(product_id).
        2. TỒN KHO: Xem tại 'stock' của 'product_variants'.
        3. LOẠI GIAO DỊCH: 'IMPORT' là Nhập, 'EXPORT' là Xuất trong bảng 'transactions'.
        4. TRẠNG THÁI XÓA: Luôn thêm 'is_deleted = false' cho categories, products, product_variants.
        5. THƯƠNG HIỆU: Là 'category_name'.
        6. VAI TRÒ: 'MANAGER' (Quản lý) hoặc 'STAFF' (Nhân viên).
             QUY TẮC DỮ LIỆU (QUAN TRỌNG):
        7. Khi so sánh màu sắc hoặc kích thước, LUÔN dùng toán tử ILIKE hoặc hàm LOWER() để tránh lỗi chữ hoa chữ thường.
        Ví dụ: pv.color ILIKE '%đen%' hoặc pv.color ILIKE '%black%'
        8. Nếu người dùng hỏi 'màu đen', hãy kiểm tra xem trong DB là 'đen' hay 'black'. 
        (Kiệt kiểm tra lại DB của bồ xem đang lưu kiểu gì rồi sửa dòng này nhé).
        9. Cột 'size' trong DB có thể là kiểu chuỗi, hãy đảm bảo so sánh đúng định dạng.
    """)

    # Nạp thêm ví dụ mẫu (Few-shot) để AI bớt "ngáo"
    vn.train(
        question="Những sản phẩm nào sắp hết hàng?",
        sql="SELECT p.product_name, pv.size, pv.color, pv.stock FROM products p JOIN product_variants pv ON p.product_id = pv.product_id WHERE pv.stock < 5 AND pv.is_deleted = false AND p.is_deleted = false;"
    )
    
    print("--- ✅ Đã luyện xong! Vui lòng comment lại hàm train_warehouse() ---")

#train_warehouse() # Chạy 1 lần rồi đóng dấu # lại

# =========================================================
# 5. FASTAPI ROUTES
# =========================================================
app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

class ChatRequest(BaseModel):
    query: str

@app.post("/ask")
async def ask_warehouse(request: ChatRequest):
    try:
        print(f"\n--- USER QUERY: {request.query} ---")
        
        # 1. Tạo SQL và truy vấn lấy dữ liệu
        # Bước này Vanna làm rất tốt, cứ để nó làm.
        sql, df, fig = vn.ask(request.query, print_results=False)

        if not sql:
            return {"status": "error", "answer": "Tôi không hiểu câu hỏi này hoặc không tìm thấy bảng phù hợp."}

        # 2. Xử lý tóm tắt kết quả (Đoạn này hay bị lỗi dictionary)
        if df is not None and not df.empty:
            # Lấy 5 dòng đầu để AI tóm tắt cho nhanh, đỡ tốn VRAM
            data_context = df.to_dict('records')[:5]
            
            prompt = f"""
            Dựa trên kết quả truy vấn từ hệ thống kho giày: {data_context}
            Hãy trả lời câu hỏi: '{request.query}' một cách ngắn gọn, chuyên nghiệp bằng tiếng Việt.
            """
            
            try:
                # Cách 1: Thử dùng Vanna (nếu nó không lỗi)
                answer = vn.submit_prompt(prompt)
            except Exception:
                # Cách 2: Nếu Vanna lỗi 'dictionary', ta lấy kết quả thô từ dataframe luôn cho an toàn
                # Ví dụ: "Kết quả: 150"
                first_val = df.iloc[0, 0]
                answer = f"Theo dữ liệu trong kho, kết quả là: {first_val}"
        else:
            answer = "Hệ thống đã kiểm tra nhưng hiện tại không có dữ liệu nào khớp với yêu cầu của bồ."

        return {
            "status": "success",
            "sql": sql,
            "answer": answer.strip()
        }

    except Exception as e:
        print(f"[CRITICAL ERROR] {str(e)}")
        # Trả về câu trả lời tối thiểu nếu mọi thứ đều sập
        return {"status": "error", "answer": "Có lỗi khi xử lý dữ liệu. Bồ kiểm tra lại kết nối Database hoặc Ollama nhé."}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)